config/routes.rb
Rails.application.routes.draw do
  get '/' => 'sessions#welcome'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/signup' => 'users#new'
  delete '/logout' => 'sessions#destroy'
  get '/auth/google_oauth2/callback' => 'sessions#omniauth'
  resources :reviews 
  resources :games do 
    resources :reviews, only: [:new, :index, :show]
  end
  resources :genres
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
    belongs_to :genre
    belongs_to :user
    has_many :reviews
    has_many :users, through: :reviews
    accepts_nested_attributes_for :genre
    validates :game_name, uniqueness: true, presence: true

    def game_name_and_genre
        "#{game_name} - #{genre.genre_name}"
    end

    def self.alpha
        order(:game_name)
    end

end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :games
    validates :genre_name, uniqueness: true, presence: true

    def self.alpha
        order(:genre_name)
    end

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :game

  validates :title, :content, presence: true
  validates :rating, numericality: {only_integer: true, greater_than_or_equal_to: 0, less_than: 11}
  
  validates :game, uniqueness: { scope: :user, message: "has already been reviewed by you" }

  

end

app/models/user.rb
class User < ApplicationRecord
    has_many :reviews
    has_many :reviewed_games, through: :reviews, source: :game
    has_many :games
    has_secure_password
    validates :username, uniqueness: true, presence: true 

    def self.create_by_google_oauth2(auth)
    self.find_or_create_by(username: auth[:info][:email]) do |u|
        u.password = SecureRandom.hex
        end
    end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :logged_in?
    private
    def logged_in?
        !!session[:user_id]
    end

    def current_user
        @current_user ||= User.find_by_id(session[:user_id])
    end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
    def new 
        @game = Game.new
        @game.build_genre
    end
    def create
       @game = Game.new(game_params)
       @game.user_id = session[:user_id]
       if @game.save
        redirect_to game_path(@game)
       else
        render :new 
       end 
    end

    def index 
        @games = Game.all.order(:game_name) 
    end

    def show 
        @reviews = Review.find_by(id: params[:id])
        @game = Game.find_by(id: params[:id])     
    end

    private
    def game_params
        params.require(:game).permit(:game_name, :genre_id, genre_attributes: [:genre_name])
    end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
    def index 
        @genres = Genre.all.order(:genre_name) 
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    def new
        if @game = Game.find_by_id(params[:game_id])
        @review = @game.reviews.build
        else
            @review = Review.new
        end
    end

    def index
        if @game = Game.find_by_id(params[:game_id])
            @reviews = @game.reviews
        else
            @reviews = Review.all.order(rating: :desc)
        end
    end

    def create 
        @review = current_user.reviews.build(review_params)
        if @review.save
            redirect_to review_path(@review)
        else
            render :new
        end
    end

    def show 
        @review = Review.find_by_id(params[:id])
    end

    private
    def review_params
        params.require(:review).permit(:game_id, :content, :rating, :title)
    end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def create
       @user = User.find_by(username: params[:user][:username])
        
       if @user && @user.authenticate(params[:user][:password])
        session[:user_id] = @user.id 
        redirect_to user_path(@user)
       else
        flash[:error] = "Incorrect, please try again."
        redirect_to login_path
       end
    end

    def destroy
        session.delete(:user_id)
        redirect_to '/'
    end

    def omniauth
        @user = User.create_by_google_oauth2(auth)
        session[:user_id] = @user.id
        redirect_to user_path(@user)
    end

    private

        def auth
            request.env['omniauth.auth']
        end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to user_path(@user)
        else
            render :new
        end
    end

    def show 
        @user = User.find_by_id(params[:id])
        redirect_to '/' if !@user
        
        redirect_to "/games"
    end

    private
    def user_params
        params.require(:user).permit(:username, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/games/index.html.erb
<h1>Sign Up Successful, Welcome! </h1>
<h3>Is your game missing?<%= link_to "Add a Game", new_game_path %></h3>
<% @games.each do |ga| %>
    <h2><%= link_to ga.game_name, game_reviews_path(ga) %> - <%= ga.genre.genre_name %></h2>
    <%= link_to "Write a Review", new_game_review_path(ga.id) %>
<% end %>

app/views/games/new.html.erb
<h1>New Game Form Here</h1>
<%= render partial: 'layouts/errors', locals: {object: @game} %>
<%= form_for(@game) do |f| %>
    <div>
        <%= f.label :game_name %>
        <%= f.text_field :game_name %>
    </div>

    <p>Select a Genre or Create a New Genre</p>
    <div>
        <%= f.collection_select :genre_id, Genre.all.alpha, :id, :genre_name, include_blank: 'Select One' %>
    </div>
    <br>
    <div>
        <%= f.fields_for :genre do |g| %>
            <%= g.label :genre_name %>
            <%= g.text_field :genre_name %>
            <% end %>
    </div>
    <br>
    <%= f.submit %>
<% end %>

app/views/games/show.html.erb
<h1><%= @game.game_name %> - <%= @game.genre.genre_name %></h1>
<h2>Leave a review for this game <%= link_to 'here!', new_review_path %></h2>
<%= link_to @reviews.title, review_path %> - <%= @reviews.rating%>

app/views/genres/index.html.erb
<h1>All Genres</h1>
<h3>Is your game or genre missing? Add it <%= link_to "here!", new_game_path %></h3>
<ol>
    <% @genres.each do |genre| %>
    <li><%= genre.genre_name %></li>
    <% end %>
</ol>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
    <div id="error_explanation">
        <h2><%= pluralize(object.errors.count, "error") %> prohibited this from being saved:</h2>
        <ul>
            <% object.errors.full_messages.each do |msg|%>
            <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GameReviewProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <div>
    <% if logged_in? %>
    <%= link_to "Home", games_path %>
    <br>
    <%= link_to "All Reviews", reviews_path %>
    <br>
    <%= link_to "All Genres", genres_path %>
    <br>
    <%= link_to "Logout", logout_path, method: :delete %>
    <% end %>
  </div>

  <body>
    <%= yield %>
  </body>
</html>

app/views/reviews/index.html.erb
<% if @game %>
    <h1>Reviews for <%= @game.game_name %> - <%= @game.genre.genre_name %></h1>
<% else %>
    <h1>All Reviewed Games</h1>
<% end %>
<h3>See a Game you would like to review? Tell us what you think and <%=link_to "leave a review!", new_review_path %></h3>
<h3>Maybe you don't see the game you want to review? <%= link_to "Add a New Game!", new_game_path %></h3>
<ol>
    <% @reviews.each do |r| %>
    <li><%= r.game.game_name %>: <%= link_to r.title, review_path(r) %> - <%= r.rating %></li> <br>
    <% end %>
</ol>

app/views/reviews/new.html.erb
<% if params[:game_id] %>
    <h1>Add a new Review for <%= @review.game.game_name %> - <%= @review.game.genre.genre_name %></h1>
<% else %>
    <h1>Create a Review</h1>
<% end %>

<%= render partial: 'layouts/errors', locals: {object: @review} %>
<%= form_for(@review) do |f| %>
    <% if params[:game_id] %>
    <%= f.hidden_field :game_id %>
    <% else %>
    <div>
        <%= f.label :game_id, "Select a Game" %>
        <%= f.collection_select :game_id, Game.all.alpha, :id, :game_name_and_genre, include_blank: true %>
    </div>
    <% end %>
    <div>
        <%= f.label :score %>
        <%= f.number_field :rating, min:0, max:10 %>
    </div>
    <br>
    <div>
        <%= f.label :title %>
        <%= f.text_field :title %>
    </div>
    <br>
    <div>
        <%= f.label :content %>
        <%= f.text_area :content, size: "50x10" %>
    </div>
    <br>
    <%= f.submit %>
<% end %>

app/views/reviews/show.html.erb
<h1><%= @review.title %> - <%= @review.rating %></h1>
<br>
<p><%= @review.content %></p>

app/views/users/new.html.erb
<h1>Sign up Below</h1>
<%= render partial: 'layouts/errors', locals: {object: @user} %>
<%= form_for(@user) do |f| %>
    <%= f.label :username %>
    <%= f.text_field :username %>

    <%= f.label :password %>
    <%= f.password_field :password %>

    <%= f.submit "Sign Up" %>
<% end %>